/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'siravi' at '12/9/16 5:06 PM' with Gradle 2.13
 *
 * @author siravi, @date 12/9/16 5:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
